FILENAME REFFILE '/home/u63329560/DATA/sales_data3.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV 
	OUT=WORK.IMPORT;
	GETNAMES=YES;
RUN;

/*add option Replace*/
FILENAME REFFILE '/home/u63329560/DATA/sales_data3.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV REPLACE
	OUT=WORK.IMPORT;
	GETNAMES=YES ;
	GUESSINGROWS=1000 ;
RUN;

